### PR TITLE
Fix numbers in icon name not converted to non-numeric 

### PR DESCRIPTION
**Pull request by exoego**
Addresses https://github.com/fomantic/Fomantic-UI/issues/1544

Currently, only single numeric character is converted to English word.
However, like `stopwatch-20`, two-or-more numeric chars are not converted.

# Before

* `500px` => `['500px']` ✔️ 
* `wifi-1` => `wifi.1` => `['wifi', '1']` => `['wifi', 'one']` ✔️ 
* `stopwatch-20` =>`stopwatch.20` => `['stopwatch', '20']` ❌ 

# After

* `500px` => `['500px']` ✔️ 
* `wifi-1` => `wifi.1` => `['wifi', '1']` => `['wifi', 'one']` ✔️ 
* `stopwatch-20` =>`stopwatch.20` => `['stopwatch', '20']`  => `['stopwatch', 'twenty']` ✔️ 

<del>I think thsi solution is not perfect, but more robust and small than adding all known english word like `10: 'ten', ... 20: 'twenty', ... 1000: `thousand` ...`.</del>
Leveraged https://github.com/salmanm/num-words to convert numers to appropriate English word(s), as @lubber-de suggested.

### CODE REVIEW

**Comment by lubber-de** [comment]
I don't like `twone` . Nobody will have a clue he/she has to write that instead of `twenty`

There is a nice npm package which converts all possible numbers into english words (its actually just a few lines of JS)
If you adopt this, your concerns are gone :wink:

https://www.npmjs.com/package/num-words
https://github.com/salmanm/num-words/blob/master/index.js

**Comment by exoego** [comment]
Thanks, I will update this PR to use `num-words`.

I was a bit worryying about that English words could be sometimes longer.
For example, `365` => `three hundreds and sixty five` vs `threesixfive`
However, it seems that there is no such long numeric word in FontAwesome as of today, so this is just my overthinking.
And, for future (upcoming FUI 3.0), as far as I rember, we are going to use `data` attribute instead of `class` for icons/emojis, so conversions could be much simpler.

**Comment by exoego** [comment]
Updated the PR to use `num-words`

**Comment by exoego** [comment]
Updated PR.
Yes, I agree that it could not be a problem.

[There seems other libraries for English or further multilingual support](https://www.npmjs.com/search?q=number%20english&ranking=popularity).
In terms of file size, some popular ones are relatively huge (several hundreds KB) for this simple purpose, so `num-words` maybe a good choice.

I do not have enough time to compare them so keep `num-words` as-is, but if another liblrary suggested, I will update.

**Pull request merged**
