### PR TITLE
[Font] Added support for the light font

### PR DESCRIPTION
**Pull request by synoptase**
## Description

Adds support for the light version of Fontawesome icons as per #1 .

## Note
Due to possible conflict names in icon names (https://github.com/fomantic/icon-script/issues/1#issuecomment-419746270), css rule has been named `thin`.
ie: `abacus thin` will render the `light` version of the `abacus` icon.

### CODE REVIEW

**Comment by synoptase** [comment]
@hammy2899, i'm a bit lost with the `icon.overrides.crather`. The `importLightIcons` is not yet supported by semantic-ui, therefore i don't know if all that part is correct...

The `icon.html.eco.crather` would probably use an update to display `light` examples, but i guess it's pulled from the semantic-ui repo.

**Comment by hammy2899** [comment]
@synoptase I have looked over the code and it all looks great however I will do some testing to make sure it all works before I merge.

The `icon.overrides.crather` looks correct but as you have mentioned the variables aren't in SUI yet. I will make a PR to add them into FUI tonight when I get a chance. I might make some changes to the script so that the user can select a template to use SUI or FUI which should allow people to still use the script for either project.

Thanks for the PR this is a big help 👍

**Comment by hammy2899** [comment]
I have just tried some testing and it all seems good. The only problem I have is I'm 99% sure the icon file is now so large that docpad can't compile the page to check it. I will try and do the final tests tomorrow when I have some time to mess around.

**Comment by synoptase** [comment]
All right. Thanks :)

**Comment by mwood23** [comment]
If anyone finds this and wants to add light icons to Semantic make sure you add this to the `semantic/src/themes/default/elements/icon.variables` file.  🎉

```
/* Light Icons */
@importLightIcons: true;
@lightFontName: 'thin-icons';
@lightSrc:
  url("@{fontPath}/@{lightFontName}.eot?#iefix") format('embedded-opentype'),
  url("@{fontPath}/@{lightFontName}.woff2") format('woff2'),
  url("@{fontPath}/@{lightFontName}.woff") format('woff'),
  url("@{fontPath}/@{lightFontName}.ttf") format('truetype'),
  url("@{fontPath}/@{lightFontName}.svg#icons") format('svg')
;
@lightallbackSRC: url("@{fontPath}/@{lightFontName}.eot");
```

**Comment by cosminstefanxp** [comment]
@hammy2899 , any updates on this?

**Comment by hammy2899** [comment]
@cosminstefanxp There is a few things I want to fix before merging this as mentioned in [this](https://github.com/fomantic/icon-script/pull/3#issuecomment-441273262) comment, I just haven't getting around to doing it.

**Comment by beatlecz** [comment]
Any update on this?

**Comment by hammy2899** [comment]
@beatlecz Sorry still haven't got around to doing this, if I get some free time today I will take a look otherwise I will 100% do it tonight or tomorrow.

If you need to use this sooner I would suggest just cloning the PR branch and using that.
```
$ git clone git@github.com:synoptase/icon-script.git
$ git checkout light-font-addition
```

**Comment by hammy2899** [comment]
After some testing I'm just gonna rewrite this script to allow more flexibility for generating the pro and free additions.

If anyone wants to use this change now just use the commands mentioned in my last comment.

**Comment by hammy2899** [comment]
Added with new CLI tool

https://github.com/fomantic/create-fomantic-icons

**Pull request closed without merging**
