### PR TITLE
add support for Duotone icons

### PR DESCRIPTION
**Pull request by pedobry**
This PR adds support for Dualtone icons.
CSS is generated based on Fontawesome's docs - https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

It's from my forked branch which is based on latest develop.

### CODE REVIEW

**Comment by lubber-de** [comment]
@hammy2899 Please also check the general sync between current develop and master

**Comment by lubber-de** [comment]
> @hammy2899 Please also check the general sync between current develop and master

Fixed it myself now by #99 😄

**Comment by hammy2899** [comment]
Thanks @lubber-de 🤣

**Comment by lubber-de** [comment]
Closing in favor of #203, which was based on your changes.

**Pull request closed without merging**
